#!/usr/bin/env python3
"""Emit the facts the Ghidra scripts need, from the two places that already own them.

The addresses live in include/lyrium/dao/targets.h and include/lyrium/dao/pool_patch.h;
the import thunks live in the PE itself. Neither is retyped into a .java file, so a
Ghidra run can never disagree with the DLL about what it is looking at.

  known_addresses.tsv   va, name, size, patch_len, prologue_hex, sha256
  known_imports.tsv     name, iat_va

Usage:
  tools/ghidra/emit_known_addresses.py <exe> <out_dir> [repo_root]
"""

from __future__ import annotations

import hashlib
import re
import struct
import sys
from pathlib import Path

# The memory surface we are surveying. Anything not on this list is not an
# allocation primitive and would only add noise to the xref sweep.
MEMORY_IMPORTS = (
    "VirtualAlloc",
    "VirtualFree",
    "HeapCreate",
    "HeapDestroy",
    "HeapAlloc",
    "HeapFree",
    "HeapReAlloc",
    "HeapSize",
    "HeapLock",
    "HeapUnlock",
    "GetProcessHeap",
)


class Pe:
    """Just enough PE to turn a virtual address into a file offset."""

    def __init__(self, path: Path) -> None:
        self._data = path.read_bytes()
        e_lfanew = struct.unpack_from("<I", self._data, 0x3C)[0]
        if self._data[e_lfanew : e_lfanew + 4] != b"PE\0\0":
            raise ValueError(f"{path} is not a PE image")
        coff = e_lfanew + 4
        nsec = struct.unpack_from("<H", self._data, coff + 2)[0]
        optsz = struct.unpack_from("<H", self._data, coff + 16)[0]
        self._opt = coff + 20
        self.image_base = struct.unpack_from("<I", self._data, self._opt + 28)[0]
        self._sections = []
        table = self._opt + optsz
        for i in range(nsec):
            off = table + 40 * i
            vsize, vaddr, rawsize, rawptr = struct.unpack_from("<IIII", self._data, off + 8)
            self._sections.append((vaddr, vsize, rawptr, rawsize))

    def offset_of_rva(self, rva: int) -> int | None:
        for vaddr, vsize, rawptr, rawsize in self._sections:
            if vaddr <= rva < vaddr + max(vsize, rawsize):
                offset = rva - vaddr + rawptr
                if offset < rawptr + rawsize:
                    return offset
        return None

    def offset_of_va(self, va: int) -> int | None:
        return self.offset_of_rva(va - self.image_base)

    def read_va(self, va: int, size: int) -> bytes:
        offset = self.offset_of_va(va)
        if offset is None:
            raise ValueError(f"{va:#010x} is not mapped")
        return self._data[offset : offset + size]

    def _cstring(self, rva: int) -> str:
        offset = self.offset_of_rva(rva)
        if offset is None:
            return ""
        return self._data[offset : self._data.index(b"\0", offset)].decode("latin1")

    def import_thunks(self) -> dict[str, int]:
        """Map imported symbol name to the VA of its import address table slot."""
        imp_rva = struct.unpack_from("<I", self._data, self._opt + 96 + 8)[0]
        thunks: dict[str, int] = {}
        descriptor = self.offset_of_rva(imp_rva)
        while True:
            lookup, _, _, name_rva, iat_rva = struct.unpack_from("<IIIII", self._data, descriptor)
            if lookup == 0 and name_rva == 0 and iat_rva == 0:
                break
            entry = self.offset_of_rva(lookup or iat_rva)
            slot = self.image_base + iat_rva
            while True:
                value = struct.unpack_from("<I", self._data, entry)[0]
                if value == 0:
                    break
                if not value & 0x80000000:
                    # Skip the two-byte hint that precedes the name.
                    thunks[self._cstring(value + 2)] = slot
                entry += 4
                slot += 4
            descriptor += 20
        return thunks


def parse_targets(header: str) -> list[dict]:
    """Pull the target table out of targets.h.

    Deliberately regex rather than a real parser: the file is generated by hand in a
    fixed designated-initialiser shape, and a mismatch here shows up immediately as a
    missing row in the sanity diff rather than as a wrong answer.
    """
    body = header[header.index("inline constexpr Target targets[]") :]
    targets = []
    for block in re.finditer(r"\{\s*\.name\s*=\s*\"(\w+)\"(.*?)\.prologue\s*=\s*\{([^}]*)\}", body, re.S):
        name, fields, prologue = block.groups()
        def field(key: str) -> int:
            match = re.search(rf"\.{key}\s*=\s*(0x[0-9a-fA-F]+|\d+)", fields)
            if match is None:
                raise ValueError(f"{name} has no .{key}")
            return int(match.group(1), 0)
        sha = re.search(r'\.sha256\s*=\s*"([0-9a-f]{64})"', fields)
        targets.append(
            {
                "va": field("address"),
                "name": name,
                "size": field("size"),
                "patch_len": field("patch_len"),
                "prologue": bytes(int(b, 16) for b in re.findall(r"0x[0-9a-fA-F]{2}", prologue)),
                "sha256": sha.group(1) if sha else "-",
            }
        )
    return targets


def parse_pool_site(header: str) -> dict:
    site = int(re.search(r"main_pool_site\s*=\s*std::uintptr_t\{(0x[0-9a-fA-F]+)\}", header).group(1), 0)
    opcode = re.search(r"main_pool_opcode\[\]\s*=\s*\{([^}]*)\}", header).group(1)
    default = int(re.search(r"main_pool_default\s*=\s*std::uint32_t\{(0x[0-9a-fA-F]+)\}", header).group(1), 0)
    prologue = bytes(int(b, 16) for b in re.findall(r"0x[0-9a-fA-F]{2}", opcode)) + struct.pack("<I", default)
    return {
        "va": site,
        "name": "main_pool_site",
        "size": len(prologue),
        "patch_len": 0,
        "prologue": prologue,
        "sha256": "-",
    }


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    exe = Path(sys.argv[1])
    out = Path(sys.argv[2])
    root = Path(sys.argv[3]) if len(sys.argv) > 3 else Path(__file__).resolve().parents[2]

    pe = Pe(exe)
    targets = parse_targets((root / "include/lyrium/dao/targets.h").read_text(encoding="utf-8-sig"))
    targets.append(parse_pool_site((root / "include/lyrium/dao/pool_patch.h").read_text(encoding="utf-8-sig")))

    out.mkdir(parents=True, exist_ok=True)
    rows = ["va\tname\tsize\tpatch_len\tprologue_hex\tsha256"]
    mismatched = 0
    for t in targets:
        rows.append(
            "\t".join(
                (
                    f"{t['va']:#010x}",
                    t["name"],
                    str(t["size"]),
                    str(t["patch_len"]),
                    t["prologue"].hex(),
                    t["sha256"],
                )
            )
        )
        # Confirm against the file on the way past. Everything downstream assumes the
        # exe is the build the table was recorded from; this is where that is decided.
        actual = pe.read_va(t["va"], len(t["prologue"]))
        if actual != t["prologue"]:
            print(f"PROLOGUE MISMATCH {t['name']} {t['va']:#010x}", file=sys.stderr)
            print(f"  header {t['prologue'].hex()}", file=sys.stderr)
            print(f"  exe    {actual.hex()}", file=sys.stderr)
            mismatched += 1
        if t["sha256"] != "-":
            digest = hashlib.sha256(pe.read_va(t["va"], t["size"])).hexdigest()
            if digest != t["sha256"]:
                print(f"BODY SHA MISMATCH {t['name']} {t['va']:#010x}", file=sys.stderr)
                print(f"  header {t['sha256']}", file=sys.stderr)
                print(f"  exe    {digest}", file=sys.stderr)
                mismatched += 1
    (out / "known_addresses.tsv").write_text("\n".join(rows) + "\n", encoding="utf-8")

    thunks = pe.import_thunks()
    lines = ["name\tiat_va"]
    missing = []
    for name in MEMORY_IMPORTS:
        slot = thunks.get(name)
        if slot is None:
            missing.append(name)
            continue
        lines.append(f"{name}\t{slot:#010x}")
    (out / "known_imports.tsv").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"{len(targets)} addresses, {len(lines) - 1} imports -> {out}")
    if missing:
        print(f"NOT IMPORTED: {', '.join(missing)}", file=sys.stderr)
    if mismatched:
        print(f"{mismatched} mismatch(es) against {exe}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
